services:
  agac-api:
    image: r3tr0ananas/agac-api:latest
    volumes:  
      - ./cached_images:/app/assets/cache
    ports:
      - 8000:8000/tcp 
    environment:
      ROOT_PATH: ""
    restart: unless-stopped